repldex/Repldex

commands.py

Added command ^newentry <entryname> for writing new entries
Documented command ^newentry and ^random
Should probably work, sorry if I broke something. But btw this is your fault since your lazy mat. Also bruh I had to change my tabs to spaces smh. Also making pull requests are hard

Updated commands.py

---

commands.py

made it so if similar or identical entry is found, alerts user in footer

mat is AI confirmed, updated commands.py

---

commands.py

syntax: ^link <user mention> <article>
Manually links non-editors to entries (admin only)
Probably works, but mat should really check the code cause I have no clue what I'm doing, hopefully didn't break anything, maybe.
you should;ve used discord.js smh

Added new command, link

---

commands.py

Fixed my previous error

---

templates/admin/users.html

Allow admins to click a row to sort it
Code from: https://stackoverflow.com/a/49041392

Add admin user table sort

---

config/config.json
server.py

requests is no longer used (was used for the new entry webhook), no longer is

removed usage of requests (and fixed config)

---

server.py

Instead of invoking the function during admin only routes I made it a decorator, so you can just add it and be done with it.

only admin route decorator

---

CONTRIBUTING.md
database.py
server.py

merge master

---

main.py

Just making code more readable + testing code QL

Make loading config file simpler + easier to read

---

static/main.css
templates/edit.html

Styled upload button

---

discordbot.py

Fix #43 and do gateway intents

---

betterbot.py
commands.py

Allow bots. To use certain commands

Setup bot allowed stuff

---

api.py
betterbot.py
commands.py
config.py
database.py
discordbot.py
images.py
main.py
server.py
utils.py

Fixed the majority of pep8 warnings and other miscellaneous formatting issues. Closes #46

Fix pep8 warnings

---

commands.py
discordbot.py

Make it easier to tell who did it, later we can just send tag + Id instead of ping

Add ping for log

---

discordbot.py

why it always use ^, just fixed dat

update activity to use set prefix

---

main.py
repldex/utils.py

The error was happening because `database` wasn't being imported in utils, this also closes #74

Import database in utils (fixes infinite scrolling)

---

repldex/backend/database.py
repldex/backend/website.py
repldex/discordbot/bot.py
repldex/discordbot/commands.py
repldex/utils.py
tests/__init__.py

Removed print statements that run often and could just be replaced with comments. Maybe someone can add a debug config variable that does print these?

Remove a bunch of useless print statements

---

repldex/discordbot/bot.py
repldex/discordbot/commands.py

Leon broke discord commands, this fixes them (and other command-related issues). Closes #78

Fix commands

---

repldex/discordbot/bot.py
repldex/discordbot/commands.py

Fix more command stuff

---

repldex/discordbot/commands.py

I'm not sure if we need another config such as developer.txt but currently its admin only.

make ping admin only

---

src/app.html
src/routes/__error.svelte
src/routes/edit.svelte
src/routes/entry/[slug].svelte
src/routes/index.svelte

I was bored so i added a title to "app.html"

added title to 'app.html' as needed

---

src/lib/discord/api/commands.ts
src/lib/discord/api/interactions.ts
src/lib/discord/bot.ts

The interaction when doing `handle` in bot.ts is now a lot easier to use, and it comes with TypeScript typings.

Make commands better

---

.github/workflows/ci.yml
.gitpod.yml
package.json
src/app.html
src/lib/Head.svelte
src/lib/inputs/MarkdownEditor.svelte
src/lib/inputs/TextInput.svelte
src/routes/edit/index.svelte

This checks the code with both Prettier and Eslint. Closes #188

Add a workflow that runs `npm run lint`

---

src/lib/discord/api/interactions.ts

There was a if statement that was making it impossible to verify and register interactions, this fix has made it so it works correctly

[BOT] Fixed if statement

---

src/lib/database/entries.ts

Adds the "editedAt" field and sorts by that by default.

Sort entries by when they were last edited
